insert into customer (id, name) values (1001, 'StarLight Cinema');
insert into customer (id, name) values (1002, 'MoonBeam Playhouse');
insert into customer (id, name) values (1003, 'Sunset Theatre');
insert into customer (id, name) values (1004, 'Crystal Palace Cinema');
insert into customer (id, name) values (1005, 'Grand Opera House');
insert into customer (id, name) values (1006, 'Magnolia Playhouse');
insert into customer (id, name) values (1007, 'Aurora Stage');
insert into customer (id, name) values (1008, 'Onyx Theatre');
insert into customer (id, name) values (1009, 'LunaLight Cinema');
insert into customer (id, name) values (1010, 'Golden Horizon Theatre');
insert into customer (id, name) values (1011, 'Velvet Curtain Theatre');
insert into customer (id, name) values (1012, 'Silver Screen Cinema');
insert into customer (id, name) values (1013, 'Twilight Playhouse');
insert into customer (id, name) values (1014, 'Majestic Theatre');
insert into customer (id, name) values (1015, 'Phoenix Stage');
insert into customer (id, name) values (1016, 'Orchid Cinema Hall');
insert into customer (id, name) values (1017, 'Galaxy Performing Arts Center');
insert into customer (id, name) values (1018, 'Iris Cultural Hall');
insert into customer (id, name) values (1019, 'The Rosewood Theatre');
insert into customer (id, name) values (1020, 'CineNova Multiplex');
insert into customer (id, name) values (1021, 'Magnolia Theatre');